### ISSUE TITLE
Unable  to Authorize  

### ISSUE THREAD

**Issue by vikashsingh009** [Aimprosoft/user-account-switcher#1]
Hi,

I  am  using  this  Addons  for  User  Account  Switcher ,  but  when  i  switching  user  its  giving  error  as  Forbidden  do  we  have  any  idea  what  was  issues

**Comment by isushko** [comment]
Hello. 
Could you specify more details about your issue?

**Comment by vikashsingh009** [comment]
![alfresco_switch_user](https://cloud.githubusercontent.com/assets/7962189/12957629/a8e63dd2-d053-11e5-9b7a-12262624ae71.png)
here is  the  Catelina.out  logs

 ERROR [login.webscript.LoginSwitcherWebScript] [http-apr-8080-exec-11] User switching is failed due to an error :
{
    "status" :
  {
    "code" : 403,
    "name" : "Forbidden",
    "description" : "Server understood the request but refused to fulfill it."
  },

  "message" : "01100004 Login failed",
  "exception" : "org.springframework.extensions.webscripts.WebScriptException - 01100004 Login failed",

  "callstack" :
  [
          ""      ,"org.springframework.extensions.webscripts.WebScriptException: 01100004 Login failed"

**Comment by vikashsingh009** [comment]
I  am  using  Alfresco  Community  version  5.1 ,  i  had  followed  the  same  steps  mentioned  in  doc

**Comment by isushko** [comment]
Thank you for your information. Unfortunately we didn't test in under alfresco 5.1. Target was 5.0. Anyway we will adapt it to work on latest version of alfresco.

**Comment by isushko** [comment]
Is this user account enabled?
We reproduced issue but only on disabled account

**Comment by vikashsingh009** [comment]
Right  now  its  disable,  do you  want  me  to  enable  Addons  to
alfresco  server

if  yes  please  let  me  know  ,  i  will  do  it

On Fri, Feb 12, 2016 at 3:34 PM, isushko notifications@github.com wrote:

> Is this user account enabled?
> We reproduced issue but only on disabled account
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Aimprosoft/user-account-switcher/issues/1#issuecomment-183259034
> .

## 

Best Regards

VikashSingh
Bizrunttime ITServices

**Comment by isushko** [comment]
I asked about user account itself (ajit in you case). If user account disabled, you can't switch to it.

**Comment by vikashsingh009** [comment]
User  Account  ajit    is  enable  in  our  case,   i  tested  with  All
user  i  have  with  that  plugin  but non  of  work

is  is  possible  for  you  to  chat  on  skype  and  you  solve  our
issues  with  current  version

my  skype  id  is

vikash.bizruntime

On Fri, Feb 12, 2016 at 3:38 PM, isushko notifications@github.com wrote:

> I asked about user account itself (ajit in you case). If user account
> disabled, you can't switch to it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Aimprosoft/user-account-switcher/issues/1#issuecomment-183259660
> .

## 

Best Regards

VikashSingh
Bizrunttime ITServices
