### ISSUE TITLE
Plugin licence ?

### ISSUE THREAD

**Issue by asauvez** [Aimprosoft/user-account-switcher#5]
Hello and thank for your cool plugin. It work great on Alfresco 5.2 Enterprise.

Just to be sure, could you tell us what is your plugin licence, please ?

We prefer to be clean with the plugin licences we use, out of respect for their author.

Adrien

**Comment by isushko** [comment]
Hello Adrien, 

We glad that you enjoy our plugin and very happy that it would help you to make your software better.

Currently, the plugin in under Apache-2.0 license. 

Another great news, we plan to roll out a new version of the plugin in the near future (a week or two). 

Igor
